### ISSUE TITLE
Suitable for other robot arms

### ISSUE THREAD

**Issue by hnuzhy** [mihdalal/neuralmotionplanner#3]
Thank you for releasing your excellect work. I noticed that the simulated training data is based on Franka. I'm wondering if the distilled neural motion planner is suitable for driving other robot arms such as UR and WidowX. Or does the current solution not support cross-embodiment? Looking forward to your reply.

**Comment by mihdalal** [comment]
The current solution does not support cross-embodiment unfortunately, but this is something we are actively working on! Stay tuned :)

**Comment by hnuzhy** [comment]
I got it. Thx~
