### ISSUE TITLE
`ompl-1.5.2.zip` Cannot be unzipped

### ISSUE THREAD

**Issue by DavoodSZ1993** [mihdalal/neuralmotionplanner#4]
Hello,

Thanks for the great work and package. When I go through the installation procedure, when I execute the following command:

`unzip containers/ompl-1.5.2.zip`

I get the following error:
```
Archive:  containers/ompl-1.5.2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of containers/ompl-1.5.2.zip or
        containers/ompl-1.5.2.zip.zip, and cannot find containers/ompl-1.5.2.zip.ZIP, period.
```

Could you please check to address this issue.

Best,

**Comment by mihdalal** [comment]
Sorry for the delay, I just re-uploaded. Try now?

**Comment by DavoodSZ** [comment]
Hi, 

Thanks. I turned to ompl wheels for that purpose.

https://github.com/kylc/ompl-wheels/releases

Thanks
