### ISSUE TITLE
Clarification on Input Point Cloud for deploy_neural_mp.py

### ISSUE THREAD

**Issue by linden713** [mihdalal/neuralmotionplanner#5]
Hi, thank you for sharing your work! I have a question regarding the input point cloud in deploy_neural_mp.py. In the code, the input point cloud is obtained using neural_mp.get_scene_pcd(), but the paper mentions that the input should include both the scene point cloud and the point clouds of the robot arm's start and goal positions. Could you clarify why the code only uses the scene point cloud as input?

Thank you!

**Comment by mihdalal** [comment]
@Jim-Young6709

**Comment by Jim-Young6709** [comment]
Hi, we obtain the arm's start and goal point clouds directly from the 3D model of the robot. So only the scene point cloud is required as additional input.

**Comment by linden713** [comment]
Thanks for your clarification!
